//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2dff5efa_d964_42c5_98af_d418ede035b9
{
    using System;
    using CbOrm.Entity;
    using CbOrm.Storage;
    using CbOrm.Ref;
    using CbOrm.Meta;
    using System.Collections.Generic;
    using CbOrm.Blop;
    using CbOrm.App.Sys;
    
    
    public class P : CEntityObject
    {
        
        public static CbOrm.Meta.CTyp _P_TypM = new CbOrm.Meta.CTyp(typeof(P), new System.Guid("00000000-0000-0000-0000-000000000000"), P._GetProperties);
        
        private CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, System.Guid> AcGuidM;
        
        private static CSkalarRefMetaInfo _AcGuid_MetaInfoM = new CSkalarRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.P), nameof(AcGuid));
        
        private CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, System.Guid> NcGuidM;
        
        private static CSkalarRefMetaInfo _NcGuid_MetaInfoM = new CSkalarRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.P), nameof(NcGuid));
        
        private CR11CRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, Test2dff5efa_d964_42c5_98af_d418ede035b9.C> AcM;
        
        private static CR11CRefMetaInfo _Ac_MetaInfoM = new CR11CRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.P), nameof(Ac));
        
        private CR11CRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, Test2dff5efa_d964_42c5_98af_d418ede035b9.C> NcM;
        
        private static CR11CRefMetaInfo _Nc_MetaInfoM = new CR11CRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.P), nameof(Nc));
        
        public P(CStorage aStorage) : 
                base(aStorage)
        {
        }
        
        public static CbOrm.Meta.CTyp _P_Typ
        {
            get
            {
                return P._P_TypM;
            }
        }
        
        public override CbOrm.Meta.CTyp Typ
        {
            get
            {
                return P._P_Typ;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(System.Guid))]
        [CbOrm.App.Sys.CForeignKeyCounterpartTypeAttribute(typeof(P))]
        [CbOrm.App.Sys.CForeignKeyCounterpartPropertyNameAttribute("Ac")]
        public CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, System.Guid> AcGuid
        {
            get
            {
                if (Object.ReferenceEquals(this.AcGuidM, null))
                {
                    this.AcGuidM = new CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, System.Guid>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.P._AcGuid_MetaInfo);
                }
                return this.AcGuidM;
            }
        }
        
        public static CSkalarRefMetaInfo _AcGuid_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.P._AcGuid_MetaInfoM;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(System.Guid))]
        [CbOrm.App.Sys.CForeignKeyCounterpartTypeAttribute(typeof(P))]
        [CbOrm.App.Sys.CForeignKeyCounterpartPropertyNameAttribute("Nc")]
        public CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, System.Guid> NcGuid
        {
            get
            {
                if (Object.ReferenceEquals(this.NcGuidM, null))
                {
                    this.NcGuidM = new CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, System.Guid>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.P._NcGuid_MetaInfo);
                }
                return this.NcGuidM;
            }
        }
        
        public static CSkalarRefMetaInfo _NcGuid_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.P._NcGuid_MetaInfoM;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.C))]
        public CR11CRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, Test2dff5efa_d964_42c5_98af_d418ede035b9.C> Ac
        {
            get
            {
                if (Object.ReferenceEquals(this.AcM, null))
                {
                    this.AcM = new CR11CRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, Test2dff5efa_d964_42c5_98af_d418ede035b9.C>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.P._Ac_MetaInfo, Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Ac_MetaInfo);
                }
                return this.AcM;
            }
        }
        
        public static CR11CRefMetaInfo _Ac_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.P._Ac_MetaInfoM;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.C))]
        [CbOrm.App.Sys.CAutoCreateAttribute(false)]
        public CR11CRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, Test2dff5efa_d964_42c5_98af_d418ede035b9.C> Nc
        {
            get
            {
                if (Object.ReferenceEquals(this.NcM, null))
                {
                    this.NcM = new CR11CRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.P, Test2dff5efa_d964_42c5_98af_d418ede035b9.C>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.P._Nc_MetaInfo, Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Nc_MetaInfo);
                }
                return this.NcM;
            }
        }
        
        public static CR11CRefMetaInfo _Nc_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.P._Nc_MetaInfoM;
            }
        }
        
        private static void _GetProperties(System.Action<CbOrm.Meta.CRefMetaInfo> aAddProperty)
        {
            aAddProperty.Invoke(P._AcGuid_MetaInfo);
            aAddProperty.Invoke(P._NcGuid_MetaInfo);
            aAddProperty.Invoke(P._Ac_MetaInfo);
            aAddProperty.Invoke(P._Nc_MetaInfo);
        }
    }
    
    public class C : CEntityObject
    {
        
        public static CbOrm.Meta.CTyp _C_TypM = new CbOrm.Meta.CTyp(typeof(C), new System.Guid("00000000-0000-0000-0000-000000000000"), C._GetProperties);
        
        private CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, System.Guid> Parent_P_Ac_GuidM;
        
        private static CSkalarRefMetaInfo _Parent_P_Ac_Guid_MetaInfoM = new CSkalarRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.C), nameof(Parent_P_Ac_Guid));
        
        private CR11PRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, Test2dff5efa_d964_42c5_98af_d418ede035b9.P> Parent_P_AcM;
        
        private static CR11PRefMetaInfo _Parent_P_Ac_MetaInfoM = new CR11PRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.C), nameof(Parent_P_Ac));
        
        private CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, System.Guid> Parent_P_Nc_GuidM;
        
        private static CSkalarRefMetaInfo _Parent_P_Nc_Guid_MetaInfoM = new CSkalarRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.C), nameof(Parent_P_Nc_Guid));
        
        private CR11PRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, Test2dff5efa_d964_42c5_98af_d418ede035b9.P> Parent_P_NcM;
        
        private static CR11PRefMetaInfo _Parent_P_Nc_MetaInfoM = new CR11PRefMetaInfo(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.C), nameof(Parent_P_Nc));
        
        public C(CStorage aStorage) : 
                base(aStorage)
        {
        }
        
        public static CbOrm.Meta.CTyp _C_Typ
        {
            get
            {
                return C._C_TypM;
            }
        }
        
        public override CbOrm.Meta.CTyp Typ
        {
            get
            {
                return C._C_Typ;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(System.Guid))]
        public CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, System.Guid> Parent_P_Ac_Guid
        {
            get
            {
                if (Object.ReferenceEquals(this.Parent_P_Ac_GuidM, null))
                {
                    this.Parent_P_Ac_GuidM = new CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, System.Guid>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Ac_Guid_MetaInfo);
                }
                return this.Parent_P_Ac_GuidM;
            }
        }
        
        public static CSkalarRefMetaInfo _Parent_P_Ac_Guid_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Ac_Guid_MetaInfoM;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.P))]
        public CR11PRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, Test2dff5efa_d964_42c5_98af_d418ede035b9.P> Parent_P_Ac
        {
            get
            {
                if (Object.ReferenceEquals(this.Parent_P_AcM, null))
                {
                    this.Parent_P_AcM = new CR11PRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, Test2dff5efa_d964_42c5_98af_d418ede035b9.P>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Ac_MetaInfo, C._Parent_P_Ac_Guid_MetaInfo);
                }
                return this.Parent_P_AcM;
            }
        }
        
        public static CR11PRefMetaInfo _Parent_P_Ac_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Ac_MetaInfoM;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(System.Guid))]
        public CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, System.Guid> Parent_P_Nc_Guid
        {
            get
            {
                if (Object.ReferenceEquals(this.Parent_P_Nc_GuidM, null))
                {
                    this.Parent_P_Nc_GuidM = new CSkalarRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, System.Guid>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Nc_Guid_MetaInfo);
                }
                return this.Parent_P_Nc_GuidM;
            }
        }
        
        public static CSkalarRefMetaInfo _Parent_P_Nc_Guid_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Nc_Guid_MetaInfoM;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(Test2dff5efa_d964_42c5_98af_d418ede035b9.P))]
        public CR11PRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, Test2dff5efa_d964_42c5_98af_d418ede035b9.P> Parent_P_Nc
        {
            get
            {
                if (Object.ReferenceEquals(this.Parent_P_NcM, null))
                {
                    this.Parent_P_NcM = new CR11PRef<Test2dff5efa_d964_42c5_98af_d418ede035b9.C, Test2dff5efa_d964_42c5_98af_d418ede035b9.P>(this, Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Nc_MetaInfo, C._Parent_P_Nc_Guid_MetaInfo);
                }
                return this.Parent_P_NcM;
            }
        }
        
        public static CR11PRefMetaInfo _Parent_P_Nc_MetaInfo
        {
            get
            {
                return Test2dff5efa_d964_42c5_98af_d418ede035b9.C._Parent_P_Nc_MetaInfoM;
            }
        }
        
        private static void _GetProperties(System.Action<CbOrm.Meta.CRefMetaInfo> aAddProperty)
        {
            aAddProperty.Invoke(C._Parent_P_Ac_Guid_MetaInfo);
            aAddProperty.Invoke(C._Parent_P_Ac_MetaInfo);
            aAddProperty.Invoke(C._Parent_P_Nc_Guid_MetaInfo);
            aAddProperty.Invoke(C._Parent_P_Nc_MetaInfo);
        }
    }
    
    public class TestSchema : CbOrm.Schema.CSchema
    {
        
        public static TestSchema SingletonM = new TestSchema();
        
        private TestSchema()
        {
            this.AddTyp(P._P_TypM);
            this.AddTyp(C._C_TypM);
            this.Init();
        }
        
        public static TestSchema Singleton
        {
            get
            {
                return TestSchema.SingletonM;
            }
        }
        
        public static CbOrm.Schema.CSchema GetSingleton()
        {
            return TestSchema.SingletonM;
        }
    }
}
