//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3c33e931_2902_4d22_a6f7_05daa01389b7
{
    using System;
    using CbOrm.Entity;
    using CbOrm.Storage;
    using CbOrm.Ref;
    using CbOrm.Meta;
    using System.Collections.Generic;
    
    
    public enum MyEnum
    {
        
        MyField0,
        
        MyField1,
    }
    
    public class C : CEntityObject
    {
        
        public static CbOrm.Meta.CTyp _C_TypM = new CbOrm.Meta.CTyp(typeof(C), new System.Guid("00000000-0000-0000-0000-000000000000"), C._GetProperties);
        
        private CSkalarRef<Test3c33e931_2902_4d22_a6f7_05daa01389b7.C, Test3c33e931_2902_4d22_a6f7_05daa01389b7.MyEnum> MyEnumPropertyM;
        
        private static CSkalarRefMetaInfo _MyEnumPropertyMetaInfoM = new CSkalarRefMetaInfo(typeof(Test3c33e931_2902_4d22_a6f7_05daa01389b7.C), nameof(MyEnumProperty));
        
        public C(CStorage aStorage) : 
                base(aStorage)
        {
        }
        
        public static CbOrm.Meta.CTyp _C_Typ
        {
            get
            {
                return C._C_TypM;
            }
        }
        
        public override CbOrm.Meta.CTyp Typ
        {
            get
            {
                return C._C_Typ;
            }
        }
        
        [CbOrm.Attributes.CTargetTypeAttribute(typeof(Test3c33e931_2902_4d22_a6f7_05daa01389b7.C))]
        public CSkalarRef<Test3c33e931_2902_4d22_a6f7_05daa01389b7.C, Test3c33e931_2902_4d22_a6f7_05daa01389b7.MyEnum> MyEnumProperty
        {
            get
            {
                if (Object.ReferenceEquals(this.MyEnumPropertyM, null))
                {
                    this.MyEnumPropertyM = new CSkalarRef<Test3c33e931_2902_4d22_a6f7_05daa01389b7.C, Test3c33e931_2902_4d22_a6f7_05daa01389b7.MyEnum>(this, Test3c33e931_2902_4d22_a6f7_05daa01389b7.C._MyEnumPropertyMetaInfo);
                }
                return this.MyEnumPropertyM;
            }
        }
        
        public static CSkalarRefMetaInfo _MyEnumPropertyMetaInfo
        {
            get
            {
                return Test3c33e931_2902_4d22_a6f7_05daa01389b7.C._MyEnumPropertyMetaInfoM;
            }
        }
        
        private static void _GetProperties(System.Action<CbOrm.Meta.CRefMetaInfo> aAddProperty)
        {
            aAddProperty.Invoke(C._MyEnumPropertyMetaInfo);
        }
    }
    
    public class TestSchema : CbOrm.Schema.CSchema
    {
        
        public static TestSchema SingletonM = new TestSchema();
        
        private TestSchema()
        {
            this.AddTyp(C._C_TypM);
            this.RegisterEnumType(typeof(Test3c33e931_2902_4d22_a6f7_05daa01389b7.MyEnum));
            this.Init();
        }
        
        public static TestSchema Singleton
        {
            get
            {
                return TestSchema.SingletonM;
            }
        }
        
        public static CbOrm.Schema.CSchema GetSingleton()
        {
            return TestSchema.SingletonM;
        }
    }
}
